// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalRepository.Migrations
{
    [DbContext(typeof(AnimalDbContext))]
    [Migration("20240613233911_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Adoptado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("AnimalRazaId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<bool>("Genero")
                        .HasColumnType("bit");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalRazaId");

                    b.ToTable("Animal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adoptado = false,
                            AnimalRazaId = 1,
                            Edad = 5,
                            Genero = true,
                            Historia = "Max es un perrito muy amigable que adora jugar a buscar la pelota. Le encanta estar rodeado de personas y siempre está dispuesto a hacer nuevos amigos. Es un perro leal y muy cariñoso.",
                            Nombre = "Max",
                            Peso = 30.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 2,
                            Adoptado = false,
                            AnimalRazaId = 1,
                            Edad = 4,
                            Genero = false,
                            Historia = "Bella es una perra juguetona que disfruta de largos paseos y caricias en la barriga. Es muy sociable y le encanta interactuar con otros perros y personas. Bella es perfecta para una familia activa.",
                            Nombre = "Bella",
                            Peso = 28.3m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 3,
                            Adoptado = false,
                            AnimalRazaId = 2,
                            Edad = 6,
                            Genero = true,
                            Historia = "Charlie es un perro leal que adora estar cerca de su familia. A pesar de su aspecto robusto, es muy cariñoso y disfruta de los momentos de tranquilidad. Es un excelente compañero para cualquier hogar.",
                            Nombre = "Charlie",
                            Peso = 24.1m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 4,
                            Adoptado = false,
                            AnimalRazaId = 2,
                            Edad = 3,
                            Genero = false,
                            Historia = "Lucy es una perrita muy tranquila que se lleva bien con los niños. Le encanta pasar el tiempo en casa y recibir mimos. Es una perrita muy leal y cariñosa, perfecta para cualquier familia.",
                            Nombre = "Lucy",
                            Peso = 21.7m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 5,
                            Adoptado = false,
                            AnimalRazaId = 3,
                            Edad = 6,
                            Genero = true,
                            Historia = "Buddy es un Labrador Retriever lleno de energía y entusiasmo. Le encanta jugar y hacer ejercicio al aire libre. Es muy inteligente y siempre está dispuesto a aprender nuevos trucos.",
                            Nombre = "Buddy",
                            Peso = 30.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 6,
                            Adoptado = false,
                            AnimalRazaId = 3,
                            Edad = 4,
                            Genero = false,
                            Historia = "Daisy es una perrita muy cariñosa que disfruta de largas caminatas y caricias. Es perfecta para una familia que le guste el aire libre y pasar tiempo juntos. Daisy es muy leal y protectora.",
                            Nombre = "Daisy",
                            Peso = 28.3m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 7,
                            Adoptado = false,
                            AnimalRazaId = 4,
                            Edad = 5,
                            Genero = true,
                            Historia = "Rocky es un Bulldog robusto y amigable. Le gusta mucho jugar con otros perros y es muy sociable. Es un perro tranquilo que disfruta de los momentos de relajación junto a su familia.",
                            Nombre = "Rocky",
                            Peso = 24.1m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 8,
                            Adoptado = false,
                            AnimalRazaId = 4,
                            Edad = 3,
                            Genero = false,
                            Historia = "Molly es una Bulldog muy tranquila y se lleva bien con niños. Es perfecta para un hogar con niños, ya que es muy paciente y cariñosa. Molly disfruta de las siestas y de la compañía de su familia.",
                            Nombre = "Molly",
                            Peso = 21.7m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 9,
                            Adoptado = false,
                            AnimalRazaId = 5,
                            Edad = 4,
                            Genero = true,
                            Historia = "Jack es un Beagle curioso y lleno de vida. Siempre está buscando aventuras y le encanta explorar su entorno. Es muy inteligente y disfruta de los juegos de olfateo y búsqueda.",
                            Nombre = "Jack",
                            Peso = 15.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 10,
                            Adoptado = false,
                            AnimalRazaId = 5,
                            Edad = 2,
                            Genero = false,
                            Historia = "Luna es muy juguetona y le encanta olfatear todo a su alrededor. Es ideal para paseos largos y actividades al aire libre. Luna es muy cariñosa y siempre está dispuesta a jugar.",
                            Nombre = "Luna",
                            Peso = 13.8m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 11,
                            Adoptado = false,
                            AnimalRazaId = 6,
                            Edad = 5,
                            Genero = true,
                            Historia = "Cooper es un Caniche inteligente y muy entrenado. Es perfecto para un hogar que le dedique tiempo y atención. Cooper disfruta de los juegos de inteligencia y siempre está listo para aprender.",
                            Nombre = "Cooper",
                            Peso = 10.2m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 12,
                            Adoptado = false,
                            AnimalRazaId = 6,
                            Edad = 3,
                            Genero = false,
                            Historia = "Sophie es muy cariñosa y le encanta acurrucarse. Es ideal para un hogar tranquilo y amoroso. Sophie disfruta de las caricias y siempre está buscando la compañía de su familia.",
                            Nombre = "Sophie",
                            Peso = 9.7m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 13,
                            Adoptado = false,
                            AnimalRazaId = 7,
                            Edad = 6,
                            Genero = true,
                            Historia = "Bear es un Pastor Alemán muy protector. Es excelente para seguridad y compañía. Bear es muy leal y siempre está dispuesto a cuidar de su familia. Disfruta de los juegos y el ejercicio.",
                            Nombre = "Bear",
                            Peso = 35.4m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 14,
                            Adoptado = false,
                            AnimalRazaId = 7,
                            Edad = 4,
                            Genero = false,
                            Historia = "Zoe es muy leal y amigable. Le encanta estar activa y siempre está lista para jugar. Es una compañera perfecta para actividades al aire libre y disfruta de la compañía de su familia.",
                            Nombre = "Zoe",
                            Peso = 32.8m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 15,
                            Adoptado = false,
                            AnimalRazaId = 8,
                            Edad = 5,
                            Genero = true,
                            Historia = "Toby es un Golden Retriever muy cariñoso y sociable. Es perfecto para cualquier familia que busque un perro leal y amigable. Toby disfruta de los juegos y de las largas caminatas.",
                            Nombre = "Toby",
                            Peso = 29.3m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 16,
                            Adoptado = false,
                            AnimalRazaId = 8,
                            Edad = 3,
                            Genero = false,
                            Historia = "Chloe es muy dulce y se lleva bien con todos. Es ideal para un hogar con otros animales. Chloe es muy cariñosa y siempre está buscando la atención y el cariño de su familia.",
                            Nombre = "Chloe",
                            Peso = 27.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 17,
                            Adoptado = false,
                            AnimalRazaId = 9,
                            Edad = 4,
                            Genero = true,
                            Historia = "Oscar es un Chihuahua muy valiente y enérgico. Le encanta estar cerca de su dueño y es muy protector. Es ideal para una persona que busque un compañero pequeño pero lleno de carácter.",
                            Nombre = "Oscar",
                            Peso = 6.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 18,
                            Adoptado = false,
                            AnimalRazaId = 9,
                            Edad = 2,
                            Genero = false,
                            Historia = "Lola es muy juguetona y le encanta ser el centro de atención. Es perfecta para un hogar que le guste la compañía de un perro pequeño y enérgico. Lola es muy cariñosa y siempre está lista para jugar.",
                            Nombre = "Lola",
                            Peso = 5.8m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 19,
                            Adoptado = false,
                            AnimalRazaId = 10,
                            Edad = 5,
                            Genero = true,
                            Historia = "Duke es un Boxer muy activo y lleno de energía. Le encanta correr y jugar al aire libre. Es muy leal y protector, ideal para una familia que disfrute de las actividades físicas.",
                            Nombre = "Duke",
                            Peso = 28.2m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 20,
                            Adoptado = false,
                            AnimalRazaId = 10,
                            Edad = 3,
                            Genero = false,
                            Historia = "Ruby es una perrita muy juguetona y llena de vida. Disfruta de los juegos y de pasar tiempo con su familia. Es muy cariñosa y siempre está lista para una nueva aventura.",
                            Nombre = "Ruby",
                            Peso = 26.4m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 21,
                            Adoptado = false,
                            AnimalRazaId = 11,
                            Edad = 4,
                            Genero = true,
                            Historia = "Rex es un gato muy amigable y leal. Le encanta estar cerca de las personas y siempre está dispuesto a jugar. Es un gatito muy adaptable y se lleva bien con otros animales.",
                            Nombre = "Rex",
                            Peso = 25.0m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 22,
                            Adoptado = false,
                            AnimalRazaId = 11,
                            Edad = 3,
                            Genero = false,
                            Historia = "Lily es una gatita Mestiza muy dulce y cariñosa. Es perfecta para una familia que busque un compañero leal y lleno de amor. Lily disfruta de los juegos y de la compañía de su familia.",
                            Nombre = "Lily",
                            Peso = 23.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 23,
                            Adoptado = false,
                            AnimalRazaId = 12,
                            Edad = 4,
                            Genero = true,
                            Historia = "Sam es un michi muy curioso y juguetón. Le encanta explorar su entorno y hacer nuevos amigos. Es muy inteligente y siempre está dispuesto a aprender nuevas cosas.... y hacer desastres",
                            Nombre = "Sam",
                            Peso = 20.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 24,
                            Adoptado = false,
                            AnimalRazaId = 12,
                            Edad = 2,
                            Genero = false,
                            Historia = "Michifuzz es una gatita muy dulce y cariñosa. Disfruta de los juegos y de pasar tiempo con su familia. Es perfecta para un hogar amoroso y paciente.",
                            Nombre = "Michifuzz",
                            Peso = 18.9m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 25,
                            Adoptado = false,
                            AnimalRazaId = 13,
                            Edad = 3,
                            Genero = true,
                            Historia = "Simba es un gato Siamese muy curioso y lleno de energía. Le encanta explorar y jugar con juguetes interactivos. Es muy cariñoso y disfruta de la compañía de su familia.",
                            Nombre = "Simba",
                            Peso = 4.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 26,
                            Adoptado = false,
                            AnimalRazaId = 13,
                            Edad = 2,
                            Genero = false,
                            Historia = "Nala es una gatita Siamese muy juguetona y cariñosa. Disfruta de los juegos y de acurrucarse con su familia. Es perfecta para un hogar que le guste la compañía de un gato activo.",
                            Nombre = "Nala",
                            Peso = 4.2m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 27,
                            Adoptado = false,
                            AnimalRazaId = 14,
                            Edad = 4,
                            Genero = true,
                            Historia = "Leo es un gato Persa muy tranquilo y cariñoso. Le encanta pasar tiempo en casa y recibir mimos. Es ideal para un hogar que busque un compañero tranquilo y amoroso.",
                            Nombre = "Leo",
                            Peso = 5.0m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 28,
                            Adoptado = false,
                            AnimalRazaId = 14,
                            Edad = 3,
                            Genero = false,
                            Historia = "Mia es una gatita Persa muy dulce y cariñosa. Disfruta de la tranquilidad del hogar y de la compañía de su familia. Es perfecta para un hogar que le guste la compañía de un gato cariñoso.",
                            Nombre = "Mia",
                            Peso = 4.7m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 29,
                            Adoptado = false,
                            AnimalRazaId = 15,
                            Edad = 5,
                            Genero = true,
                            Historia = "Oscar es un gato Maine Coon muy juguetón y curioso. Le encanta explorar su entorno y jugar con otros gatos. Es muy cariñoso y disfruta de la compañía de su familia.",
                            Nombre = "Oscar",
                            Peso = 6.8m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 30,
                            Adoptado = false,
                            AnimalRazaId = 15,
                            Edad = 3,
                            Genero = false,
                            Historia = "Maggie es una gatita Maine Coon muy juguetona y le encanta estar en compañía de otros gatos. Disfruta de los juegos y de acurrucarse con su familia.",
                            Nombre = "Maggie",
                            Peso = 6.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 31,
                            Adoptado = false,
                            AnimalRazaId = 16,
                            Edad = 4,
                            Genero = true,
                            Historia = "Zeus es un gato Ragdoll muy cariñoso. Le encanta ser el centro de atención y recibir mimos. Es muy tranquilo y disfruta de la compañía de su familia.",
                            Nombre = "Zeus",
                            Peso = 5.9m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 32,
                            Adoptado = false,
                            AnimalRazaId = 16,
                            Edad = 2,
                            Genero = false,
                            Historia = "Daisy es una gatita Ragdoll muy dulce que busca un hogar donde pueda recibir mucho cariño. Es muy tranquila y le encanta estar cerca de su familia.",
                            Nombre = "Daisy",
                            Peso = 5.7m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 33,
                            Adoptado = false,
                            AnimalRazaId = 17,
                            Edad = 5,
                            Genero = true,
                            Historia = "Thor es un gato Bengala muy activo y juguetón. Le encanta explorar y jugar con juguetes interactivos. Es muy inteligente y disfruta de la compañía de su familia.",
                            Nombre = "Thor",
                            Peso = 6.2m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 34,
                            Adoptado = false,
                            AnimalRazaId = 17,
                            Edad = 3,
                            Genero = false,
                            Historia = "Luna es una gatita Bengala muy curiosa y llena de energía. Le encanta explorar y jugar con otros gatos. Es muy cariñosa y disfruta de la compañía de su familia.",
                            Nombre = "Luna",
                            Peso = 5.9m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 35,
                            Adoptado = false,
                            AnimalRazaId = 18,
                            Edad = 4,
                            Genero = true,
                            Historia = "Coco es un gato Sphynx muy curioso y juguetón. Le encanta estar en compañía de otros gatos y explorar su entorno. Es muy cariñoso y disfruta de la atención de su familia.",
                            Nombre = "Coco",
                            Peso = 6.0m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 36,
                            Adoptado = false,
                            AnimalRazaId = 18,
                            Edad = 3,
                            Genero = true,
                            Historia = "Milo es un gato Sphynx muy tranquilo y amoroso. Disfruta de los momentos de calma en casa y de recibir mimos. Es perfecto para un hogar que busque un gato cariñoso y tranquilo.",
                            Nombre = "Milo",
                            Peso = 5.5m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 37,
                            Adoptado = false,
                            AnimalRazaId = 19,
                            Edad = 4,
                            Genero = false,
                            Historia = "Misha es una gatita Russian Blue muy afectuosa y leal. Disfruta de los momentos tranquilos en casa y de la compañía de su familia. Es muy cariñosa y siempre está lista para recibir mimos.",
                            Nombre = "Misha",
                            Peso = 5.8m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 38,
                            Adoptado = false,
                            AnimalRazaId = 19,
                            Edad = 3,
                            Genero = true,
                            Historia = "Oliver es un gato Russian Blue muy juguetón y lleno de energía. Le encanta jugar con juguetes y explorar su entorno. Es muy cariñoso y disfruta de la compañía de su familia.",
                            Nombre = "Oliver",
                            Peso = 5.4m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 39,
                            Adoptado = false,
                            AnimalRazaId = 20,
                            Edad = 4,
                            Genero = true,
                            Historia = "Milo es un gato Scottish Fold muy tranquilo y cariñoso. Disfruta de los momentos de calma en casa y de recibir mimos. Es perfecto para un hogar que busque un compañero tranquilo y amoroso.",
                            Nombre = "Milo",
                            Peso = 6.2m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        },
                        new
                        {
                            Id = 40,
                            Adoptado = false,
                            AnimalRazaId = 20,
                            Edad = 3,
                            Genero = false,
                            Historia = "Luna es una gatita Scottish Fold muy juguetona y llena de vida. Disfruta de los juegos y de pasar tiempo con su familia. Es perfecta para un hogar amoroso y paciente.",
                            Nombre = "Luna",
                            Peso = 5.9m,
                            UsuarioId = "19BB7F593372433FB34300E75953D3A3"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AnimalRaza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("AnimalRaza", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Mestizo",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Otro",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Labrador Retriever",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Bulldog",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Beagle",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Caniche",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Pastor Aleman",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Golden Retriever",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Chihuahua",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Boxer",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Mestizo",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Otro",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Siamese",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Persa",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Maine Coon",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Ragdoll",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Bengal",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 18,
                            Descripcion = "Sphynx",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 19,
                            Descripcion = "Russian Blue",
                            TipoId = 2
                        },
                        new
                        {
                            Id = 20,
                            Descripcion = "Scottish Fold",
                            TipoId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.AnimalTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnimalTipo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Perro"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Gato"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Media", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            url = "https://live-mascotas-sanas-duenos-felices-blogs.cphostaccess.com/posts/easset_upload_file32027_708883_e.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 2,
                            url = "https://www.lt9.com.ar/uploads/s_fed89b6e647b9af00dcadfe.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 3,
                            url = "https://i0.wp.com/mascotass.com/wp-content/uploads/2011/12/Los-perros-mestizos.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 4,
                            url = "https://easyladys.com/f/7f0757e7c299623abf9089fb4d7697a5.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 5,
                            url = "https://trofeocaza.com/wp-content/uploads/2016/05/Labrador-mayor-2.jpg"
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = 6,
                            url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPm9icVOxLUGQZ7Rrae8HQR7pL0-7x0RhZr4Iy4Dtgb1DZANkMVqQkjpV-SHZ7Juio1-MELiq5h6TgUusG2QyjyaLTpwRwC3IZGfRF8nvyCcHPqIl6OZYmPNMVY1z9SXeRfCAWV5r9qtsO/s1600/10426282_807773819303512_1190001946492475051_n.jpg"
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = 7,
                            url = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjPm9icVOxLUGQZ7Rrae8HQR7pL0-7x0RhZr4Iy4Dtgb1DZANkMVqQkjpV-SHZ7Juio1-MELiq5h6TgUusG2QyjyaLTpwRwC3IZGfRF8nvyCcHPqIl6OZYmPNMVY1z9SXeRfCAWV5r9qtsO/s1600/10426282_807773819303512_1190001946492475051_n.jpg"
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = 8,
                            url = "https://ninos.kiddle.co/images/5/56/Black_French_Bull_Dog.png"
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = 9,
                            url = "https://scontent.feze8-1.fna.fbcdn.net/v/t1.6435-9/48087963_2105103709551142_3668719407355396096_n.jpg?stp=dst-jpg_s600x600&_nc_cat=111&ccb=1-7&_nc_sid=5f2048&_nc_ohc=jmjYRCLoOisQ7kNvgGqjcBw&_nc_ht=scontent.feze8-1.fna&oh=00_AYDAFytU_FRHEXZvN2CIJySg0K6qwiCokTIcIoLYrP1K0g&oe=6692F80D"
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = 10,
                            url = "https://www.tuperromiperro.com/wp-content/uploads/2022/09/Perro-Beagle.jpg"
                        },
                        new
                        {
                            Id = 11,
                            AnimalId = 11,
                            url = "https://scontent.feze8-1.fna.fbcdn.net/v/t1.6435-9/174801457_5588061661211518_8542369355131170408_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=5f2048&_nc_ohc=YnlvHl_cxrIQ7kNvgFsnN1L&_nc_ht=scontent.feze8-1.fna&oh=00_AYAYOjZ9qEe3inYjgPIXppacuO_K-9oR1DFg7X73IT0RsQ&oe=6692D40D"
                        },
                        new
                        {
                            Id = 12,
                            AnimalId = 12,
                            url = "https://www.montecaserosonline.com/galeria/caniche_toy_jazm%C3%ADn.jpg"
                        },
                        new
                        {
                            Id = 13,
                            AnimalId = 13,
                            url = "https://scontent.feze8-2.fna.fbcdn.net/v/t1.6435-9/134137059_1089190208161564_1338613731253060802_n.jpg?stp=dst-jpg_p526x296&_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_ohc=VehxKDLYl24Q7kNvgFFk-53&_nc_ht=scontent.feze8-2.fna&oh=00_AYAF2eUmtc5Cp3rXI67zrO_F6eKcSsInPBLv70qFgGhmdw&oe=6692CF93"
                        },
                        new
                        {
                            Id = 14,
                            AnimalId = 14,
                            url = "https://pbs.twimg.com/media/ELMjoz5WkAABJLx?format=jpg&name=large"
                        },
                        new
                        {
                            Id = 15,
                            AnimalId = 15,
                            url = "https://blog.dogbuddy.com/wp-content/uploads/2015/10/golden-retriever.png"
                        },
                        new
                        {
                            Id = 16,
                            AnimalId = 16,
                            url = "https://eldiariodeliamrg.wordpress.com/wp-content/uploads/2013/11/imag1350.jpg"
                        },
                        new
                        {
                            Id = 17,
                            AnimalId = 17,
                            url = "https://st4.depositphotos.com/25936512/38340/i/450/depositphotos_383405312-stock-photo-dog-car-funny-chihuahua-tiny.jpg"
                        },
                        new
                        {
                            Id = 18,
                            AnimalId = 18,
                            url = "https://i.pinimg.com/564x/aa/0d/2d/aa0d2d89bc94573e7022caeac64301d2.jpg"
                        },
                        new
                        {
                            Id = 19,
                            AnimalId = 19,
                            url = "https://www.101razasdeperros.com/images/raza-boxer-p.jpg"
                        },
                        new
                        {
                            Id = 20,
                            AnimalId = 20,
                            url = "https://www.101razasdeperros.com/images/imagenes-perros-boxer-p.jpg"
                        },
                        new
                        {
                            Id = 21,
                            AnimalId = 21,
                            url = "https://gatos.plus/wp-content/uploads/2021/11/gatos-mestizos-800x450.jpg"
                        },
                        new
                        {
                            Id = 22,
                            AnimalId = 22,
                            url = "https://scontent.feze8-1.fna.fbcdn.net/v/t1.6435-9/119518205_10159199208425639_1796140183011601986_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=5f2048&_nc_ohc=LRb2jTOvBl4Q7kNvgFAms6G&_nc_ht=scontent.feze8-1.fna&oh=00_AYArE8GmNJn_NB0MtJXTC2DeyavFSSC5rcAyAqw4PuZLjw&oe=6692E698"
                        },
                        new
                        {
                            Id = 23,
                            AnimalId = 23,
                            url = "https://scontent.feze8-2.fna.fbcdn.net/v/t1.18169-9/30704753_1792654484125840_3212093920598404223_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_ohc=30pzPupOdw8Q7kNvgEByEKT&_nc_ht=scontent.feze8-2.fna&oh=00_AYDsaORC1ckXc5gMJLNALhPxMMgwuKd48H7mSfc4rTKs8w&oe=6693005A"
                        },
                        new
                        {
                            Id = 24,
                            AnimalId = 24,
                            url = "https://static.theclinic.cl/media/2023/04/02-211346_5man_gatos-naranjas-foto-principal-880x500.jpg"
                        },
                        new
                        {
                            Id = 25,
                            AnimalId = 25,
                            url = "https://i.imgur.com/Nc6U4LF.jpeg"
                        },
                        new
                        {
                            Id = 26,
                            AnimalId = 26,
                            url = "https://c.pxhere.com/images/fa/bb/06a0b6b803cb94cc543a29e96301-1630931.jpg!d"
                        },
                        new
                        {
                            Id = 27,
                            AnimalId = 27,
                            url = "https://i.pinimg.com/564x/04/eb/87/04eb87c409b33f7ded40583ca984f196.jpg"
                        },
                        new
                        {
                            Id = 28,
                            AnimalId = 28,
                            url = "https://previews.123rf.com/images/saianoo/saianoo2206/saianoo220600234/187545230-juguet%C3%B3n-gato-de-pelo-largo-chinchilla-persa-color-gris-mascota-casera-gato-travieso.jpg"
                        },
                        new
                        {
                            Id = 29,
                            AnimalId = 29,
                            url = "https://cdn.wamiz.fr/article/images/wysiwyg/2018/12/maine-coon-maullido.jpg"
                        },
                        new
                        {
                            Id = 30,
                            AnimalId = 30,
                            url = "https://cdn.wamiz.fr/article/images/wysiwyg/2018/12/maine-coon-viento.jpg"
                        },
                        new
                        {
                            Id = 31,
                            AnimalId = 31,
                            url = "https://images.ctfassets.net/denf86kkcx7r/1k77P07O7ZcULWVVj4Q9vM/5a6e81c983c037660911e2faf13235e0/ragdoll_seguro_gato_santevet-0?fm=webp&w=913"
                        },
                        new
                        {
                            Id = 32,
                            AnimalId = 32,
                            url = "https://cdn.shopify.com/s/files/1/0268/6861/files/cat-2201013_960_720_grande.jpg?v=1530888986"
                        },
                        new
                        {
                            Id = 33,
                            AnimalId = 33,
                            url = "https://protectorabcn.es/wp-content/uploads/2021/05/Michi-5-600x600.jpg"
                        },
                        new
                        {
                            Id = 34,
                            AnimalId = 34,
                            url = "https://gatoanimal.com/wp-content/uploads/2020/04/gato-bengali-1024x768.jpg"
                        },
                        new
                        {
                            Id = 35,
                            AnimalId = 35,
                            url = "https://i.pinimg.com/564x/96/e5/bd/96e5bd432f867f9818b4e467e3ce1a9f.jpg"
                        },
                        new
                        {
                            Id = 36,
                            AnimalId = 36,
                            url = "https://t2.ea.ltmcdn.com/es/posts/8/4/8/cuidados_de_un_gato_sphynx_21848_600.webp"
                        },
                        new
                        {
                            Id = 37,
                            AnimalId = 37,
                            url = "https://www.zooplus.es/magazine/wp-content/uploads/2017/10/Gato-azul-ruso.jpg"
                        },
                        new
                        {
                            Id = 38,
                            AnimalId = 38,
                            url = "https://i.pinimg.com/564x/c8/d4/5d/c8d45d6f816341957b0265d154759988.jpg"
                        },
                        new
                        {
                            Id = 39,
                            AnimalId = 39,
                            url = "https://previews.123rf.com/images/irrmago/irrmago1806/irrmago180600194/103504744-gato-scottish-fold-mojado-durante-el-ba%C3%B1o-gracioso-gato-crema-triste-con-orejas-dobladas-se-sienta.jpg"
                        },
                        new
                        {
                            Id = 40,
                            AnimalId = 40,
                            url = "https://scontent.feze8-1.fna.fbcdn.net/v/t1.18169-9/11665701_1173980795961480_3603978141588056168_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=5f2048&_nc_ohc=rdBxOm4wflIQ7kNvgHPmu2n&_nc_ht=scontent.feze8-1.fna&oh=00_AYC8eP4fr-EpC8ylnHqkSMfzo5TPBhmbRU6wqXSK9GuWcg&oe=669304F8"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.HasOne("Domain.Entities.AnimalRaza", "Raza")
                        .WithMany("Animales")
                        .HasForeignKey("AnimalRazaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raza");
                });

            modelBuilder.Entity("Domain.Entities.AnimalRaza", b =>
                {
                    b.HasOne("Domain.Entities.AnimalTipo", "Tipo")
                        .WithMany("Razas")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Domain.Entities.Media", b =>
                {
                    b.HasOne("Domain.Entities.Animal", "Animal")
                        .WithMany("Media")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Domain.Entities.Animal", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.AnimalRaza", b =>
                {
                    b.Navigation("Animales");
                });

            modelBuilder.Entity("Domain.Entities.AnimalTipo", b =>
                {
                    b.Navigation("Razas");
                });
#pragma warning restore 612, 618
        }
    }
}
